# Generated by Django 5.2.6 on 2025-09-25 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('superadmin', 'SuperAdmin'), ('staff_l1', 'Staff L1'), ('staff_l2', 'Staff L2')], default='staff_l2', max_length=20),
        ),
    ]
