# Generated by Django 5.2.6 on 2025-09-30 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_rename_mobile_user_mobilno_user_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='mobilNo',
        ),
    ]
