# Generated by Django 5.2.6 on 2025-09-30 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_remove_user_mobilno'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='mobile',
            field=models.CharField(default=1234567890, max_length=10),
            preserve_default=False,
        ),
    ]
