# Generated by Django 5.2.6 on 2025-09-27 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_tickethistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='mobile_no',
            field=models.CharField(blank=True, default='Not Provided', max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='sender_name',
            field=models.CharField(blank=True, default='Anonymous', max_length=100, null=True),
        ),
    ]
