# Generated by Django 5.2.6 on 2025-09-28 16:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0002_subdepartment'),
        ('tickets', '0004_ticket_attachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='sub_department',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to='departments.subdepartment'),
        ),
    ]
