# Generated by Django 5.2.6 on 2025-09-30 12:18

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0007_alter_ticket_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='status_changed_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('rejected', 'Rejected'), ('in_progress', 'In Progress'), ('closed', 'Closed'), ('escalated', 'Escalated')], default='pending', max_length=20),
        ),
    ]
